print('Comenzaremos con los retos del punto 3 "Invento mis reglas"\n')
print("Promedio de 2 números.\nComo ya sabemos el promedio se calcula diviendo la suma de los valores entre la cantidad de valores.\n")
valor1 = int(input("Ingresa el primer valor: "))
valor2 = int(input("\nIngresa el segundo valor: "))
print("\nEl promedio es: ", (valor1+valor2)/2,".\n")
print("Ahora el segundo reto será calcular la potencia de un número.\nPrimero se ingresará la base y luego el exponente.\n")
x = int(input("Ingresa la base: "))
y = int(input("\nIngresa el exponente: "))
print("\nEl resultado es ", x**y,".")
print("\nAhora calcularemos la raíz cuadrada de cualquier número.\n")
z = int(input("Solo necesitas ingresar el número: "))
print("\nLa raíz es ",z**0.5,".")
print("Ahora algo más dificil, obtendremos la raiz cuadrada de la suma de los cuadrados de dos números, comencemos.\n")
n1 = int(input("Ingresa el primer valor: "))
n2 = int(input("\nIngresa el segundo valor: "))
print("El resultado es ",((n1**2)+(n2**2))**0.5,".\n")